rname="tinycurl779libressl"
rver="$(cwver_tinycurl779)"
rdir="$(cwdir_tinycurl779)"
rfile="$(cwfile_tinycurl779)"
rdlfile="$(cwdlfile_tinycurl779)"
rurl="$(cwurl_tinycurl779)"
rsha256="$(cwsha256_tinycurl779)"
rreqs="libressl libssh2libressl"
. "${cwrecipe}/tinycurl/tinycurl.sh.common"
