rname="tinycurl779wolfssl"
rver="$(cwver_tinycurl779)"
rdir="$(cwdir_tinycurl779)"
rfile="$(cwfile_tinycurl779)"
rdlfile="$(cwdlfile_tinycurl779)"
rurl="$(cwurl_tinycurl779)"
rsha256="$(cwsha256_tinycurl779)"
rreqs="wolfssl libssh2wolfssl"
. "${cwrecipe}/tinycurl/tinycurl.sh.common"
