rname="tinycurlopenssl"
rver="$(cwver_tinycurl)"
rdir="$(cwdir_tinycurl)"
rfile="$(cwfile_tinycurl)"
rdlfile="$(cwdlfile_tinycurl)"
rurl="$(cwurl_tinycurl)"
rsha256=""
rreqs="openssl libssh2"
. "${cwrecipe}/tinycurl/tinycurl.sh.common"
