rname="tinycurl772wolfssl"
rver="$(cwver_tinycurl772)"
rdir="$(cwdir_tinycurl772)"
rfile="$(cwfile_tinycurl772)"
rdlfile="$(cwdlfile_tinycurl772)"
rurl="$(cwurl_tinycurl772)"
rsha256="$(cwsha256_tinycurl772)"
rreqs="wolfssl libssh2wolfssl"
. "${cwrecipe}/tinycurl/tinycurl.sh.common"
