#!/bin/bash

#
# lots of bashisms
#   can likely work with ash/dash with...
#     - BASH_SOURCE[0] replaced with $(realpath $_) - must be first command
#       - or not, $0/$_ isn't consistent across shells, $_ is funky in posix
#     - ${...//::/:} doesn't seem to work in dash
#     - this all sucks
#
# XXX - need a short-circuit env var to bail out before profile.d/local.d sourcing
#

#
# if you just want the functions:
# . <(for f in $(grep '() {$' /usr/local/crosware/etc/profile | cut -f1 -d'(') ; do sed -n '/^'${f}'() {$/,/^}$/!d;p' /usr/local/crosware/etc/profile ; done)
#

# XXX - probably need realpath in the chain here somewhere
# get our etc and bin dir
if [ -z "${BASH_VERSION}" ] ; then
  export cwetcdir="/usr/local/crosware/etc"
else
  export cwetcdir="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)"
fi
export cwetc="${cwetcdir}"
export cwtop="$(cd "${cwetcdir}"/.. && pwd)"
export cwbindir="${cwtop}/bin"
export cwsw="${cwtop}/software"

# CPPFLAGS - includes
: ${CPPFLAGS:=""}
export CPPFLAGS

# LDFLAGS - libraries
: ${LDFLAGS:=""}
export LDFLAGS

# pkg-config
: ${PKG_CONFIG_LIBDIR:=""}
: ${PKG_CONFIG_PATH:=""}
export PKG_CONFIG_LIBDIR PKG_CONFIG_PATH

# simple path functions
#   https://github.com/ryanwoodsmall/shell-ish/blob/master/lib/path-functions.sh
append_path() {
  if $(echo ${PATH} | tr ':' '\n' | grep -q -- "^${1}$") ; then
    return
  fi
  export PATH="${PATH}:${1}"
}
prepend_path() {
  export PATH="${1}:${PATH}"
}
append_cppflags() {
  if $(echo ${CPPFLAGS} | tr ' ' '\n' | grep -q -- "^${1}$") ; then
    return
  fi
  export CPPFLAGS="${CPPFLAGS} ${1}"
}
prepend_cppflags() {
  export CPPFLAGS="${1} ${CPPFLAGS}"
}
append_ldflags() {
  if $(echo ${LDFLAGS} | tr ' ' '\n' | grep -q -- "^${1}$") ; then
    return
  fi
  export LDFLAGS="${LDFLAGS} ${1}"
}
prepend_ldflags() {
  export LDFLAGS="${1} ${LDFLAGS}"
}
append_pkgconfigpath() {
  if $(echo ${PKG_CONFIG_PATH} | tr ':' '\n' | grep -q -- "^${1}$") ; then
    return
  fi
  export PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:${1}"
  export PKG_CONFIG_PATH="${PKG_CONFIG_PATH//::/:}"
  export PKG_CONFIG_LIBDIR="${PKG_CONFIG_PATH}"
}
prepend_pkgconfigpath() {
  export PKG_CONFIG_PATH="${1}:${PKG_CONFIG_PATH}"
  export PKG_CONFIG_PATH="${PKG_CONFIG_PATH//::/:}"
  export PKG_CONFIG_LIBDIR="${PKG_CONFIG_PATH}"
}

# add our bin dir to our path
append_path "${cwbindir}"

# profile.d holds packages' profile scriplets
# local.d holds custom scriptlets
profiled="profile.d"
locald="local.d"
for d in ${profiled} ${locald} ; do
  for p in ${cwetcdir}/${d}/*.sh ; do
    test -r "${p}" && . "${p}"
  done
  unset p
done
unset d profiled locald
