#!/bin/bash
#
# top-level crosware stuff only
#
: ${cwetcdir:="/usr/local/crosware/etc"}
export cwetc="${cwetcdir}"
export cwtop="$(cd "${cwetcdir}"/.. && pwd)"
export cwbindir="${cwtop}/bin"
export cwsw="${cwtop}/software"
