rname="tinyemulibressl"
rver="$(cwver_tinyemu)"
rdir="$(cwdir_tinyemu)"
rfile="$(cwfile_tinyemu)"
rdlfile="$(cwdlfile_tinyemu)"
rurl="$(cwurl_tinyemu)"
rsha256=""
rreqs="curllibressl libssh2libressl libressl"
. "${cwrecipe}/${rname%%libressl}/${rname%%libressl}.sh.common"
