rname="curlgnutlsminimal"
rreqs="gnutlsminimal nettleminimal"
rproviderreqs="${rreqs// /,}"
rcommonopts="LIBS='-lgnutls -lhogweed -lnettle -latomic'"
. "${cwrecipe}/${rname%gnutlsminimal}/${rname%gnutlsminimal}tlsprovider.sh.common"
