#!/usr/bin/env bash
#
# jgitsh? jgit.sh? org.eclipse.....sh?
#
set -eu

: ${cwtop:="/usr/local/crosware"}
: ${cwsw:="${cwtop}/software"}
: ${jgitsh:="${cwsw}/jgitsh/current/bin/jgitsh"}
: ${origin:="origin"}
: ${branch:="master"}

if [[ "${#}" == 1 ]] ; then
  if [[ "${1}" == pull ]] ; then
    "${jgitsh}" fetch "${origin}"
    "${jgitsh}" merge "${origin}/${branch}"
    exit "${?}"
  fi
fi

"${jgitsh}" "${@}"
