rname="lynxnetbsdcurseslibressl"
rver="$(cwver_lynx)"
rdir="$(cwdir_lynx)"
rfile="$(cwfile_lynx)"
rdlfile="$(cwdlfile_lynx)"
rurl="$(cwurl_lynx)"
rsha256=""
rreqs="libressl netbsdcurses"

. "${cwrecipe}/lynx/lynx.sh.common"
